// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztjlwbsdmtmebihtlayj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0amx3YnNkbXRtZWJpaHRsYXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzk5MzUsImV4cCI6MjA1ODg1NTkzNX0.cZrXEfLRxJbqCQSTjyHiECK_sjnK88GM4EqMWpRCNdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);